### ISSUE TITLE
unauthorized: empty `Authorization` header"

### ISSUE THREAD

**Issue by anonyphoenix** [okto-hq/okto-sdk-react#9]
Here there is an import:

https://github.com/okto-hq/okto-sdk-react/blob/787e8a0b0deecbf8629b40c98840f366c0cfc56e/example/app/layout.tsx#L7

but the file doesn't exist.

This is the error I get when I run the example code:

```
XHRGET
https://sandbox-api.okto.tech/api/v1/user_from_token
[HTTP/2 401  330ms]

1

{"status":"error","error":{"code":401,"errorCode":"ER-TECH-0007","message":"Unauthorised","trace_id":"69164483379483a41e06b2ef52b28df3","details":"unauthorized: empty `Authorization` header"}}


```

**Comment by oviawork** [comment]
this example is deprecated, please check the template project - https://github.com/okto-hq/okto-sdk-react-template-app for an example
